openapi: 3.1.0
info:
  title: Redocly Museum API
  description: Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
  version: 1.1.0
  termsOfService: 'https://redocly.com/subscription-agreement/'
  contact:
    email: team@redocly.com
    url: 'https://redocly.com/docs/cli/'
  license:
    name: MIT
    url: 'https://opensource.org/license/mit/'
paths:
  /users:
    get:
      summary: Returns a list of users.
      operationId: getPetsById,
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
